#!/bin/sh
# run - shell script to invoke an okami program
# Copyright (C) 2018 Wolfgang Jaehrling
#
# ISC License
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

if [ -n "`echo "$0" | grep 'dev$'`" ]; then
    mode=dev
else
    mode=run
fi

if [ \( ! -f okami \) -o $mode = dev ]; then
    echo -n rebuilding...
    as=`which arm-linux-gnueabihf-as`
    ld=`which arm-linux-gnueabihf-ld`
    if [ -z "$as" ]; then
        as=as
        ld=ld
    fi
    ($as okami.s -o okami.o && $ld okami.o -o okami) \
        || (echo \ failed; exit 1)
    echo \ ok
fi

if [ $mode = dev ]; then
    basefiles='
      lib/core.ok
      lib/hex.ok
      lib/os/io.ok
      lib/os/tty.ok
      lib/dev/debug.ok
   '
else
  basefiles='lib/core.ok'
fi

if [ -z "$1" ]; then
    runfile=/dev/null
else
    if [ -d "$1" ]; then
        runfile="$1"/Runfile
    else
        runfile="$1"
    fi
fi

if [ ! \( -e "$runfile" -a ! -d "$runfile" \) ]; then
    echo "Runfile invalid: $runfile"
    exit 1
fi

rlwrap=`which rlwrap`
$rlwrap ./okami $basefiles `cat "$runfile" | sed -e 's/#.*$//g'`
