#!/bin/sh

if [ -n "`echo "$0" | grep 'dev$'`" ]; then
    basefiles='
      lib/core.ok
      lib/hex.ok
      lib/os/io.ok
      lib/os/tty.ok
      lib/dev/debug.ok
   '
else
  basefiles='lib/core.ok'
fi

if [ -z "$1" ]; then
    runfile=/dev/null
else
    if [ -d "$1" ]; then
        runfile="$1"/Runfile
    else
        runfile="$1"
    fi
fi

if [ ! \( -e "$runfile" -a ! -d "$runfile" \) ]; then
    echo "Runfile invalid: $runfile"
    exit 1
fi

make && rlwrap ./okami $basefiles `cat "$runfile" | sed -e 's/#.*$//g'`
